### ISSUE TITLE
The GPU process has crashed

### ISSUE THREAD

**Issue by yumin9822** [cc12703/zsxqFileDownloader#1]
我在windows10,64位系统，python3.8.5下，运行出错如下：
[0908/203133.044:WARNING:gpu_process_host.cc(1256)] The GPU process has crashed 1 time(s)

DevTools listening on ws://127.0.0.1:2931/devtools/browser/9da198ab-82b6-48c0-8920-c340e5e1a997
[0908/203133.044:WARNING:gpu_process_host.cc(1256)] The GPU process has crashed 2 time(s)
[0908/203133.059:WARNING:gpu_process_host.cc(1256)] The GPU process has crashed 3 time(s)

过了几分钟出现继续出现下面错误
Traceback (most recent call last):
  File "start.py", line 69, in <module>
    main(sys.argv[1:])
  File "start.py", line 59, in main
    if not __checkTokenValid() :
  File "start.py", line 39, in __checkTokenValid
    driver = webdriver.Chrome(options=options)
  File "C:\Users\yumin4\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\yumin4\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\yumin4\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\yumin4\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yumin4\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

**Comment by aka-chestnut** [comment]
同环境测试了一下把中间几个headless参数删了就可以

**Comment by JoeAliao** [comment]
> 同环境测试了一下把中间几个headless参数删除了就可以

删除之后报：DevTools listening on ws://127.0.0.1:12240/devtools/browser/f67b8974-fef2-4142-9221-40817f9e33b8
[12168:4284:1221/015646.539:ERROR:device_event_log_impl.cc(211)] [01:56:46.539] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: 连到系统上的设备没有发挥作用。 (0x1F)

**Comment by YHMSword** [comment]
也遇到同样问题，解决后出现如下问题，应该怎么做呢？
![1](https://user-images.githubusercontent.com/22000596/106572474-68461580-6573-11eb-9c39-5d8df2b390ab.png)
